#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf VTK
rm -rf constant/cellToRegion constant/polyMesh/sets
rm -rf 0/topWall
rm -rf 0/Helium
rm -f 0/cellToRegion
rm -rf constant/topWall/polyMesh
rm -rf constant/Helium/polyMesh

# ----------------------------------------------------------------- end-of-file
