#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication splitMeshRegions -cellZones -overwrite

# remove fluid fields from solid regions (important for post-processing)
for i in topWall
do
   rm -f 0*/$i/{mut,alphat,epsilon,k,U,p_rgh}
done

for i in Helium topWall
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done


#-- Run on single processor
runApplication `getApplication`
if [ "$?" != "0" ]; then
  exit 1
fi
rm -rf log.postProcess.sample
runApplication -s sample postProcess -func sample -noZero -region Helium
# rm -rf log.postProcess.sample
# runApplication -s sample postProcess -func sample2 -noZero -region topWall

## Decompose
#runApplication decomposePar -allRegions
#

# Run OpenFOAM
#runParallel $(getApplication) &
## Run
#runParallel `getApplication` 2
#
## Reconstruct
#runApplication reconstructPar -allRegions
#runApplication -s sample postProcess -func sample -noZero -region Helium

echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll


# ----------------------------------------------------------------- end-of-file
