#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#
## Reconstruct
runApplication reconstructPar -allRegions
rm -rf log.postProcess.sample
runApplication -s sample postProcess -func sample -noZero -region Helium
rm -rf log.postProcess.sample
runApplication -s sample postProcess -func sample2 -noZero -region topWall

echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

rm -rf process*


# ----------------------------------------------------------------- end-of-file
