# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layoutMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 700)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.labelButtonHFM = QtWidgets.QLabel(self.centralwidget)
        self.labelButtonHFM.setGeometry(QtCore.QRect(20, 460, 100, 115))
        self.labelButtonHFM.setMouseTracking(True)
        self.labelButtonHFM.setText("")
        self.labelButtonHFM.setObjectName("labelButtonHFM")
        self.groupboxDynamicRegion = QtWidgets.QGroupBox(self.centralwidget)
        self.groupboxDynamicRegion.setGeometry(QtCore.QRect(20, 20, 460, 420))
        self.groupboxDynamicRegion.setTitle("")
        self.groupboxDynamicRegion.setObjectName("groupboxDynamicRegion")
        self.labelAnimationMascot = QtWidgets.QLabel(self.groupboxDynamicRegion)
        self.labelAnimationMascot.setGeometry(QtCore.QRect(20, 200, 200, 200))
        self.labelAnimationMascot.setText("")
        self.labelAnimationMascot.setObjectName("labelAnimationMascot")
        self.labelDialogBox = QtWidgets.QLabel(self.groupboxDynamicRegion)
        self.labelDialogBox.setGeometry(QtCore.QRect(40, 23, 400, 157))
        self.labelDialogBox.setText("")
        self.labelDialogBox.setObjectName("labelDialogBox")
        self.labelDialogContent = QtWidgets.QLabel(self.groupboxDynamicRegion)
        self.labelDialogContent.setGeometry(QtCore.QRect(60, 43, 360, 117))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDialogContent.setFont(font)
        self.labelDialogContent.setText("")
        self.labelDialogContent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelDialogContent.setWordWrap(True)
        self.labelDialogContent.setObjectName("labelDialogContent")
        self.labelButtonPP = QtWidgets.QLabel(self.centralwidget)
        self.labelButtonPP.setGeometry(QtCore.QRect(80, 562, 100, 115))
        self.labelButtonPP.setMouseTracking(True)
        self.labelButtonPP.setText("")
        self.labelButtonPP.setObjectName("labelButtonPP")
        self.labelButtonStart = QtWidgets.QLabel(self.centralwidget)
        self.labelButtonStart.setGeometry(QtCore.QRect(430, 622, 50, 58))
        self.labelButtonStart.setMouseTracking(True)
        self.labelButtonStart.setText("")
        self.labelButtonStart.setObjectName("labelButtonStart")
        self.labelButtonSM = QtWidgets.QLabel(self.centralwidget)
        self.labelButtonSM.setGeometry(QtCore.QRect(140, 460, 100, 115))
        self.labelButtonSM.setMouseTracking(True)
        self.labelButtonSM.setText("")
        self.labelButtonSM.setObjectName("labelButtonSM")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HammerHead"))
