#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication splitMeshRegions -cellZones -overwrite

# remove fluid fields from solid regions (important for post-processing)
for i in topWall
do
   rm -f 0*/$i/{mut,alphat,epsilon,k,U,p_rgh}
done

for i in Helium topWall
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done


#-- Run on single processor
#runApplication `getApplication`
#runApplication -s sample postProcess -func sample -noZero -region Helium

## Decompose
runApplication decomposePar -allRegions


# ----------------------------------------------------------------- end-of-file
