#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication -s sample postProcess -func sample -noZero -region Helium

## Decompose
#runApplication decomposePar -allRegions
#

# Run OpenFOAM
#runParallel $(getApplication) &
## Run
#runParallel `getApplication` 2
#
## Reconstruct
#runApplication reconstructPar -allRegions
#runApplication -s sample postProcess -func sample -noZero -region Helium

echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll


# ----------------------------------------------------------------- end-of-file
