layers: [2, 3]          # Number of hidden layers for NN architecture
modes: 10               # Number of PCA modes to train with
neurons: [16, 32]       # Number of neurons per layer for NN architecture
samples: 10             # Number of times training is performed (each time with unique random hyperparameter initialisation)
validationSplit: [0.35, 0.65]  # Ratio of data used for validation (0.35 = 35% used for validation, 65% used for training)
